@startuml

actor User as actor
control RegistrationService as service
collections RegistrationRepository as repository
activate service

actor -> service : createUser(name, pass)
service -> repository : save(User)
service <- repository
actor <- service
deactivate service


@enduml
